### ISSUE TITLE
New build, single button mode not working, can't flash.

### ISSUE THREAD

**Issue by dabonetn** [LinuxJedi/AmigaRGBtoHDMI#8]
I just built up a board, and trying the Beta36 software, and I can't get the menus to work, it acts like it's not in single button mode, so it just returns to the main menu, and if I hold it down it turns scanlines on and off.

the default.txt has been copied from Amiga_CPLD_Readme\Amiga_CPLD_Setup\Profiles to the root of the card.
And the next to the last line is.

single_button_mode=1

Any suggestions? I've tried 4gb and 32gb cards, formatted fat32 with 4k clusters.

**Comment by LinuxJedi** [comment]
Hi,

The instructions state you need to copy:
* `Amiga_CPLD_Readme/Amiga_CPLD_Setup/profile_6-12_BIT_RGB.txt` to the root of the SD card
* `Amiga_CPLD_Readme/Amiga_CPLD_Setup/Profiles/Default.txt` to the `Profiles` directory

Copying `Default.txt` to the root instead of the `Profiles` directory will not overwrite the stock `Default.txt` and therefore will not enable `single_button_mode`.

**Comment by dabonetn** [comment]
That was it.. Problem lies between keyboard and chair.. Thanks..
